{
  "hash": "86b2c26974a18259e790855ae3388fba",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Role of Targeted Therapy after Surgical Resection of Colorectal Liver Metastases\nauthor:\n  - name: JM HAN\n    corresponding: false\n    roles:\n      - manuscript writing\n    affiliations:\n      - name: KIRAMS\n        department: Department of General Surgery\n  - name: Ui Sep Shin\n    orcid: 0000-0002-1714-7469\n    corresponding: true\n    roles: \n      - Formal Analysis\n      - Supervision\n    affiliations:\n      - name: KIRAMS\n        department: Department of General Surgery\n    email: uisupshin@kirams.re.kr\nkeywords:\n  - colorectal cancer\n  - liver metastases\n  - preoperative chemotherapy\n  - survival\nabstract: |\nbibliography: references.bib\nnumber-sections: true\n# editor_options: \n#   chunk_output_type: inline\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nsource_directory<-\"source\"\nsource_filename<-\"my_functions.R\"\n\nproject_path <<- getwd()\nsource_path <<- file.path(project_path, source_directory)\nsource_path_filename <- file.path(source_path, source_filename)\nsource(source_path_filename)\n\n# source_filename<-\"mycphwt.R\"\n# source_path_filename <- file.path(source_path, source_filename)\n# source(source_path_filename)\n\nrm(source_directory, source_filename, project_path, source_path, source_path_filename)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nlibrary(readxl)\n\nraw_data_directory<-\"raw_data\"\nraw_data_filename<-\"deidentified_han20230213.xlsx\"\n\nproject_path <<- getwd()\nraw_data_path <<- file.path(project_path, raw_data_directory)\nraw_data_path_filename <- file.path(raw_data_path, raw_data_filename)\nraw_data <- read_excel(raw_data_path_filename)\n\nrm(raw_data_directory, raw_data_filename, project_path, raw_data_path, raw_data_path_filename)\n\n# 교육적 목적으로 원본 데이터를 inital_raw_data에 복사해 두고 필요시 비교합니다.\ninitial_raw_data<-raw_data\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# raw_data의 컬럼중에서 결측치가 cut-off 값 (아래에서는 5%) 이상이면 컬럼 삭제\n# 어떤 컬럼이 삭제되는지 NA수와 함께 출력함.\n# 실행을 원치 않으면 옵션 eval: false로 변경하면 됨\n\ncleaned_data<-my_eliminate_NA_columns(raw_data, 5)\n```\n\n::: {.cell-output .cell-output-stdout .hidden}\n\n```\nColumns with NAs above the threshold:\n과거.암병력: 142 NAs\nComobidity..MI.CHF.PVD.CVA.dementia.COPD.CD.PU.LD.DM.hemipl.CKD..: 78 NAs\nCOMMENT: 150 NAs\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\ncleaned_data <- my_eliminate_NA_rows(cleaned_data)\nraw_data <- cleaned_data\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nlibrary(dplyr)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n\nAttaching package: 'dplyr'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nThe following objects are masked from 'package:stats':\n\n    filter, lag\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nThe following objects are masked from 'package:base':\n\n    intersect, setdiff, setequal, union\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nraw_data <- raw_data %>% \n  select(MRN, PreHR_chemo,  PreHR_TA, Adjuvant_Doublet, Adju_TA, Any_TA, AGE, SEX, ASA, CCI, SIDENESS, pT4, pT, pN, tN, L, N, V, Diff, Synch_M1, M1_12m, BILOBE, NUM_HM, MULTI4, HM_SIZE, SIZE4, preHR_CEA, Post_HR_target_all, FU_DFS, DEATH, FU_OS, RECUR)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nselected_data <- subset(raw_data, Adjuvant_Doublet==1)\nHAN<-selected_data\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nlibrary(survival)\nlibrary(maxstat)\n\n# maxstat.test를 위한 time object 생성\nHAN$TS_DFS=Surv(HAN$FU_DFS, HAN$RECUR==\"1\") #time object\n\n# 변수파생\nHAN$LNR<-HAN$pN/HAN$tN\n\n# optimal cut-off를 찾기 위한 maxstat.test\nmaxstat.test(TS_DFS~ preHR_CEA, data=HAN,smethod=\"LogRank\",pmethod=\"condMC\",B=999)\n```\n\n::: {.cell-output .cell-output-stdout .hidden}\n\n```\n\nMaximally selected LogRank statistics using condMC\n\ndata:  TS_DFS by preHR_CEA\nM = 2.6206, p-value = 0.1161\nsample estimates:\nestimated cutpoint \n             73.97 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nmaxstat.test(TS_DFS~ CCI, data=HAN,smethod=\"LogRank\",pmethod=\"condMC\",B=999)\n```\n\n::: {.cell-output .cell-output-stdout .hidden}\n\n```\n\nMaximally selected LogRank statistics using condMC\n\ndata:  TS_DFS by CCI\nM = 0.92138, p-value = 0.6997\nsample estimates:\nestimated cutpoint \n                 7 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nmaxstat.test(TS_DFS~ ASA, data=HAN,smethod=\"LogRank\",pmethod=\"condMC\",B=999)\n```\n\n::: {.cell-output .cell-output-stdout .hidden}\n\n```\n\nMaximally selected LogRank statistics using condMC\n\ndata:  TS_DFS by ASA\nM = 0.25305, p-value = 0.7908\nsample estimates:\nestimated cutpoint \n                 2 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nmaxstat.test(TS_DFS~ NUM_HM, data=HAN,smethod=\"LogRank\",pmethod=\"condMC\",B=999)\n```\n\n::: {.cell-output .cell-output-stdout .hidden}\n\n```\n\nMaximally selected LogRank statistics using condMC\n\ndata:  TS_DFS by NUM_HM\nM = 2.9713, p-value = 0.01001\nsample estimates:\nestimated cutpoint \n                 4 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nmaxstat.test(TS_DFS~ HM_SIZE, data=HAN,smethod=\"LogRank\",pmethod=\"condMC\",B=999)\n```\n\n::: {.cell-output .cell-output-stdout .hidden}\n\n```\n\nMaximally selected LogRank statistics using condMC\n\ndata:  TS_DFS by HM_SIZE\nM = 1.2944, p-value = 0.7968\nsample estimates:\nestimated cutpoint \n                 4 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nmaxstat.test(TS_DFS~ LNR, data=HAN,smethod=\"LogRank\",pmethod=\"condMC\",B=999)\n```\n\n::: {.cell-output .cell-output-stdout .hidden}\n\n```\n\nMaximally selected LogRank statistics using condMC\n\ndata:  TS_DFS by LNR\nM = 1.3978, p-value = 0.6356\nsample estimates:\nestimated cutpoint \n         0.1818182 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# maxstat. optimal cut-off에 따른 이분화\nHAN$CEA73<-ifelse(HAN$preHR_CEA>73,1,0)\nHAN$CCI7<-ifelse(HAN$CCI>7,1,0)\nHAN$CCI7<-ifelse(HAN$CCI>7,\"CCI>7\",\"CCI<7\")\nHAN$ASA3<-ifelse(HAN$ASA>2,1,0)\n\n# 저자의 직관에 의한 이분화\nHAN$AGE60<-ifelse(HAN$AGE>60,1,0)\n\n# categorical 변수의 숫자화 ?\nHAN$PD<-ifelse(HAN$Diff==\"PD\",1,0)\nHAN$Pni1<-ifelse(HAN$N==\"Y\",1,0)\nHAN$Vi1<-ifelse(HAN$V==\"Y\",1,0)\nHAN$Lvi1<-ifelse(HAN$L==\"Y\",1,0)\nHAN$Male<-ifelse(HAN$SEX==1,1,0)\nHAN$RTCOL<-ifelse(HAN$SIDENESS==\"Rt\",1,0)\n\n# 요인화\nHAN$Adju_target<-ifelse(HAN$Post_HR_target_all==\"None\",0,ifelse(HAN$Post_HR_target_all==\"Avastin\",1,2))\nHAN$Adju_target <-as.factor(HAN$Adju_target)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nlibrary(moonBook)\n\ntable1<-mytable(Adju_TA~AGE+Male+Synch_M1+M1_12m+ASA3+CCI7+RTCOL+LNR+pT4+Pni1+Lvi1+Vi1+PD+BILOBE+MULTI4+SIZE4+preHR_CEA+CEA73+PreHR_chemo+PreHR_TA+Post_HR_target_all,\n                show.total=TRUE, exact=TRUE, data=HAN, method = 3)\ntable1\n```\n\n::: {.cell-output .cell-output-stdout .hidden}\n\n```\n\n                    Descriptive Statistics by 'Adju_TA'                    \n———————————————————————————————————————————————————————————————————————————— \n                           0                1              Total         p  \n                         (N=77)           (N=61)          (N=138)     \n———————————————————————————————————————————————————————————————————————————— \n AGE                  59.0 ± 10.5      59.1 ±  9.0      59.1 ±  9.8    0.974\n Male                                                                  0.888\n   - 0                 22 (28.6%)       19 (31.1%)       41 (29.7%)         \n   - 1                 55 (71.4%)       42 (68.9%)       97 (70.3%)         \n Synch_M1                                                              0.121\n   - M0                12 (15.6%)       17 (27.9%)       29 (21.0%)         \n   - M1                65 (84.4%)       44 (72.1%)      109 (79.0%)         \n M1_12m                                                                0.025\n   - M0                7 ( 9.1%)        15 (24.6%)       22 (15.9%)         \n   - M1                70 (90.9%)       46 (75.4%)      116 (84.1%)         \n ASA3                                                                  0.382\n   - 0                 60 (77.9%)       52 (85.2%)      112 (81.2%)         \n   - 1                 17 (22.1%)       9 (14.8%)        26 (18.8%)         \n CCI7                                                                  1.000\n   - CCI<7             37 (48.1%)       29 (47.5%)       66 (47.8%)         \n   - CCI>7             40 (51.9%)       32 (52.5%)       72 (52.2%)         \n RTCOL                                                                 0.961\n   - 0                 63 (81.8%)       51 (83.6%)      114 (82.6%)         \n   - 1                 14 (18.2%)       10 (16.4%)       24 (17.4%)         \n LNR                 0.1 [ 0.0; 0.2]  0.1 [ 0.0; 0.3]  0.1 [ 0.0; 0.3] 0.476\n pT4                                                                   0.211\n   - 0                 64 (83.1%)       56 (91.8%)      120 (87.0%)         \n   - 1                 13 (16.9%)       5 ( 8.2%)        18 (13.0%)         \n Pni1                                                                  0.599\n   - 0                 46 (59.7%)       40 (65.6%)       86 (62.3%)         \n   - 1                 31 (40.3%)       21 (34.4%)       52 (37.7%)         \n Lvi1                                                                  0.032\n   - 0                 42 (54.5%)       45 (73.8%)       87 (63.0%)         \n   - 1                 35 (45.5%)       16 (26.2%)       51 (37.0%)         \n Vi1                                                                   0.619\n   - 0                 54 (70.1%)       46 (75.4%)      100 (72.5%)         \n   - 1                 23 (29.9%)       15 (24.6%)       38 (27.5%)         \n PD                                                                    1.000\n   - 0                 74 (96.1%)       58 (95.1%)      132 (95.7%)         \n   - 1                 3 ( 3.9%)        3 ( 4.9%)        6 ( 4.3%)          \n BILOBE                                                                0.468\n   - 0                 46 (59.7%)       41 (67.2%)       87 (63.0%)         \n   - 1                 31 (40.3%)       20 (32.8%)       51 (37.0%)         \n MULTI4                                                                0.183\n   - 0                 65 (84.4%)       45 (73.8%)      110 (79.7%)         \n   - 1                 12 (15.6%)       16 (26.2%)       28 (20.3%)         \n SIZE4                                                                 0.392\n   - 0                 66 (85.7%)       48 (78.7%)      114 (82.6%)         \n   - 1                 11 (14.3%)       13 (21.3%)       24 (17.4%)         \n preHR_CEA           9.2 [ 3.2;25.1]  7.3 [ 4.8;44.4]  8.3 [ 3.7;28.0] 0.394\n CEA73                                                                 0.445\n   - 0                 70 (90.9%)       52 (85.2%)      122 (88.4%)         \n   - 1                 7 ( 9.1%)        9 (14.8%)        16 (11.6%)         \n PreHR_chemo                                                           0.028\n   - 0                 61 (79.2%)       37 (60.7%)       98 (71.0%)         \n   - 1                 16 (20.8%)       24 (39.3%)       40 (29.0%)         \n PreHR_TA                                                              0.000\n   - 0                 75 (97.4%)       40 (65.6%)      115 (83.3%)         \n   - 1                 2 ( 2.6%)        21 (34.4%)       23 (16.7%)         \n Post_HR_target_all                                                    0.000\n   - Avastin            0 ( 0.0%)       42 (68.9%)       42 (30.4%)         \n   - Erbitux            0 ( 0.0%)       19 (31.1%)       19 (13.8%)         \n   - None             77 (100.0%)        0 ( 0.0%)       77 (55.8%)         \n———————————————————————————————————————————————————————————————————————————— \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nout_u=mycph(TS_DFS~Adju_TA+Any_TA+Adju_target+SEX+AGE60+CCI7+RTCOL+LNR+pT4+Pni1+Lvi1+Vi1+PD+BILOBE+MULTI4+SIZE4+CEA73+M1_12m+PreHR_chemo+PreHR_TA, data=HAN)\n```\n\n::: {.cell-output .cell-output-stdout .hidden}\n\n```\n\n mycph : perform coxph of individual expecting variables\n\n Call: TS_DFS ~ Adju_TA + Any_TA + Adju_target + SEX + AGE60 + CCI7 +     RTCOL + LNR + pT4 + Pni1 + Lvi1 + Vi1 + PD + BILOBE + MULTI4 +     SIZE4 + CEA73 + M1_12m + PreHR_chemo + PreHR_TA, data= HAN \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nout_u\n```\n\n::: {.cell-output .cell-output-stdout .hidden}\n\n```\n               HR  lcl  ucl     p\nAdju_TA      1.48 0.96 2.28 0.074\nAny_TA       1.48 0.96 2.27 0.075\nAdju_target1 1.36 0.84 2.18 0.208\nAdju_target2 1.89 1.00 3.56 0.049\nSEX          0.89 0.57 1.40 0.620\nAGE60        0.92 0.60 1.41 0.704\nCCI7CCI>7    0.82 0.53 1.25 0.352\nRTCOL        1.08 0.63 1.87 0.773\nLNR          1.62 0.56 4.67 0.375\npT4          1.19 0.63 2.25 0.582\nPni1         1.23 0.80 1.89 0.347\nLvi1         1.07 0.69 1.64 0.774\nVi1          1.72 1.09 2.70 0.019\nPD           0.79 0.25 2.50 0.688\nBILOBE       1.57 1.02 2.43 0.040\nMULTI4       2.18 1.32 3.59 0.002\nSIZE4        1.30 0.76 2.21 0.333\nCEA73        2.00 1.13 3.56 0.018\nM1_12mM1     1.43 0.76 2.69 0.270\nPreHR_chemo  1.44 0.91 2.27 0.123\nPreHR_TA     1.87 1.10 3.21 0.022\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nout_m<-coxph(TS_DFS~Any_TA+SEX+AGE60+Vi1+BILOBE+MULTI4+CEA73, data=HAN)\n\nextractHR(out_m)\n```\n\n::: {.cell-output .cell-output-stdout .hidden}\n\n```\n         HR  lcl  ucl     p\nAny_TA 1.59 1.00 2.54 0.050\nSEX    1.00 0.63 1.58 0.987\nAGE60  0.91 0.59 1.41 0.668\nVi1    1.65 1.04 2.63 0.033\nBILOBE 1.38 0.77 2.50 0.282\nMULTI4 1.50 0.77 2.92 0.236\nCEA73  1.54 0.84 2.82 0.161\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nDFS_step<-step(out_m, direction=\"backward\")\n```\n\n::: {.cell-output .cell-output-stdout .hidden}\n\n```\nStart:  AIC=738.38\nTS_DFS ~ Any_TA + SEX + AGE60 + Vi1 + BILOBE + MULTI4 + CEA73\n\n         Df    AIC\n- SEX     1 736.38\n- AGE60   1 736.56\n- BILOBE  1 737.50\n- MULTI4  1 737.78\n- CEA73   1 738.19\n<none>      738.38\n- Any_TA  1 740.23\n- Vi1     1 740.69\n\nStep:  AIC=736.38\nTS_DFS ~ Any_TA + AGE60 + Vi1 + BILOBE + MULTI4 + CEA73\n\n         Df    AIC\n- AGE60   1 734.56\n- BILOBE  1 735.50\n- MULTI4  1 735.78\n- CEA73   1 736.26\n<none>      736.38\n- Any_TA  1 738.23\n- Vi1     1 738.71\n\nStep:  AIC=734.56\nTS_DFS ~ Any_TA + Vi1 + BILOBE + MULTI4 + CEA73\n\n         Df    AIC\n- BILOBE  1 733.59\n- MULTI4  1 734.16\n<none>      734.56\n- CEA73   1 734.57\n- Any_TA  1 736.25\n- Vi1     1 736.78\n\nStep:  AIC=733.59\nTS_DFS ~ Any_TA + Vi1 + MULTI4 + CEA73\n\n         Df    AIC\n<none>      733.59\n- CEA73   1 733.77\n- Any_TA  1 734.45\n- Vi1     1 735.68\n- MULTI4  1 737.41\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nCox_step_dfs<-extractHR(DFS_step)\nCox_step_dfs\n```\n\n::: {.cell-output .cell-output-stdout .hidden}\n\n```\n         HR  lcl  ucl     p\nAny_TA 1.46 0.94 2.25 0.091\nVi1    1.63 1.03 2.58 0.038\nMULTI4 1.92 1.16 3.18 0.011\nCEA73  1.59 0.88 2.87 0.122\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nwrite.csv(Cox_step_dfs, file=\"Cox_step_DFS.csv\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nHAN$TS_OS=Surv(HAN$FU_OS, HAN$DEATH==1) #time object\nfit_OS <-survfit(HAN$TS_OS~Adju_TA, data=HAN)\n\nout_u_os=mycph(TS_OS~Adju_TA+SEX+AGE60+CCI7+RTCOL++LNR+pT4+Pni1+Lvi1+Vi1+PD, data=HAN) # Univariate\n```\n\n::: {.cell-output .cell-output-stdout .hidden}\n\n```\n\n mycph : perform coxph of individual expecting variables\n\n Call: TS_OS ~ Adju_TA + SEX + AGE60 + CCI7 + RTCOL + +LNR + pT4 + Pni1 +     Lvi1 + Vi1 + PD, data= HAN \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nout_u_os\n```\n\n::: {.cell-output .cell-output-stdout .hidden}\n\n```\n            HR  lcl  ucl     p\nAdju_TA   1.37 0.82 2.28 0.227\nSEX       1.10 0.65 1.88 0.716\nAGE60     1.23 0.76 1.99 0.394\nCCI7CCI>7 1.13 0.70 1.83 0.613\nRTCOL     1.14 0.63 2.06 0.655\nLNR       1.64 0.46 5.86 0.449\npT4       1.39 0.74 2.59 0.304\nPni1      1.20 0.74 1.96 0.453\nLvi1      0.81 0.49 1.34 0.407\nVi1       1.80 1.09 2.99 0.023\nPD        0.98 0.24 4.02 0.979\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nout_m_os<-coxph(TS_OS~Adju_TA+SEX+AGE60+CCI7+RTCOL++LNR+pT4+Pni1+Lvi1+Vi1+PD, data=HAN)\nextractHR(out_m_os)\n```\n\n::: {.cell-output .cell-output-stdout .hidden}\n\n```\n            HR  lcl   ucl     p\nAdju_TA   1.38 0.81  2.35 0.232\nSEX       1.12 0.64  1.93 0.697\nAGE60     2.27 0.30 16.89 0.424\nCCI7CCI>7 0.49 0.07  3.71 0.491\nRTCOL     1.02 0.55  1.90 0.943\nLNR       1.69 0.41  6.92 0.463\npT4       1.30 0.65  2.58 0.462\nPni1      1.06 0.62  1.81 0.839\nLvi1      0.63 0.35  1.12 0.113\nVi1       2.01 1.11  3.66 0.022\nPD        0.78 0.17  3.55 0.748\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nlibrary(survminer)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nLoading required package: ggplot2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nLoading required package: ggpubr\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n\nAttaching package: 'survminer'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nThe following object is masked from 'package:survival':\n\n    myeloma\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nDFS_all<-survfit(Surv(FU_DFS, RECUR==\"1\")~1, data=HAN)\n\nsummary(DFS_all)\n```\n\n::: {.cell-output .cell-output-stdout .hidden}\n\n```\nCall: survfit(formula = Surv(FU_DFS, RECUR == \"1\") ~ 1, data = HAN)\n\n time n.risk n.event survival std.err lower 95% CI upper 95% CI\n    1    137       3    0.978  0.0125        0.954        1.000\n    2    133       1    0.971  0.0144        0.943        0.999\n    3    131       7    0.919  0.0235        0.874        0.966\n    4    123       3    0.896  0.0262        0.847        0.949\n    5    119       2    0.881  0.0278        0.828        0.938\n    6    117       3    0.859  0.0300        0.802        0.920\n    7    114       3    0.836  0.0320        0.776        0.901\n    8    110       4    0.806  0.0342        0.741        0.876\n    9    105       6    0.760  0.0371        0.690        0.836\n   10     96       4    0.728  0.0388        0.656        0.808\n   11     92       5    0.689  0.0405        0.614        0.773\n   12     86       8    0.624  0.0426        0.546        0.714\n   13     77       4    0.592  0.0434        0.513        0.683\n   14     73       6    0.543  0.0441        0.463        0.637\n   15     65       3    0.518  0.0444        0.438        0.613\n   17     62       3    0.493  0.0445        0.413        0.589\n   18     58       1    0.485  0.0446        0.405        0.580\n   19     56       2    0.467  0.0446        0.388        0.564\n   20     53       4    0.432  0.0446        0.353        0.529\n   21     49       1    0.423  0.0446        0.344        0.520\n   23     47       1    0.414  0.0445        0.336        0.511\n   24     46       3    0.387  0.0443        0.310        0.485\n   26     42       1    0.378  0.0442        0.301        0.475\n   27     41       1    0.369  0.0440        0.292        0.466\n   28     40       3    0.341  0.0435        0.266        0.438\n   36     37       1    0.332  0.0433        0.257        0.429\n   43     36       1    0.323  0.0431        0.248        0.419\n   69     20       1    0.307  0.0439        0.232        0.406\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nmin(HAN$FU_DFS)\n```\n\n::: {.cell-output .cell-output-stdout .hidden}\n\n```\n[1] 0\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nmax(HAN$FU_DFS)\n```\n\n::: {.cell-output .cell-output-stdout .hidden}\n\n```\n[1] 161\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nmedian(HAN$FU_DFS)\n```\n\n::: {.cell-output .cell-output-stdout .hidden}\n\n```\n[1] 14\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nmedian(HAN$FU_OS)\n```\n\n::: {.cell-output .cell-output-stdout .hidden}\n\n```\n[1] 45.5\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nmin(HAN$FU_OS)\n```\n\n::: {.cell-output .cell-output-stdout .hidden}\n\n```\n[1] 1\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nmax(HAN$FU_OS)\n```\n\n::: {.cell-output .cell-output-stdout .hidden}\n\n```\n[1] 170\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nsum(HAN$RECUR)\n```\n\n::: {.cell-output .cell-output-stdout .hidden}\n\n```\n[1] 85\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nsum(HAN$DEATH)\n```\n\n::: {.cell-output .cell-output-stdout .hidden}\n\n```\n[1] 67\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nDFS<-survfit(Surv(FU_DFS, RECUR==\"1\")~Adju_TA, data=HAN)\nsummary(DFS)\n```\n\n::: {.cell-output .cell-output-stdout .hidden}\n\n```\nCall: survfit(formula = Surv(FU_DFS, RECUR == \"1\") ~ Adju_TA, data = HAN)\n\n                Adju_TA=0 \n time n.risk n.event survival std.err lower 95% CI upper 95% CI\n    1     76       1    0.987  0.0131        0.962        1.000\n    2     74       1    0.974  0.0185        0.938        1.000\n    3     72       3    0.933  0.0290        0.878        0.991\n    4     69       3    0.892  0.0360        0.825        0.966\n    5     65       2    0.865  0.0397        0.790        0.946\n    6     63       1    0.851  0.0414        0.774        0.936\n    7     62       1    0.837  0.0430        0.757        0.926\n    8     61       3    0.796  0.0470        0.709        0.894\n    9     57       2    0.768  0.0493        0.678        0.871\n   10     54       4    0.711  0.0532        0.614        0.824\n   11     50       1    0.697  0.0540        0.599        0.812\n   12     48       2    0.668  0.0556        0.568        0.786\n   13     46       2    0.639  0.0568        0.537        0.761\n   14     44       4    0.581  0.0586        0.477        0.708\n   15     40       1    0.566  0.0589        0.462        0.695\n   17     39       1    0.552  0.0592        0.447        0.681\n   18     38       1    0.537  0.0594        0.433        0.667\n   19     36       2    0.508  0.0597        0.403        0.639\n   20     34       1    0.493  0.0598        0.388        0.625\n   23     33       1    0.478  0.0598        0.374        0.611\n   24     32       2    0.448  0.0597        0.345        0.582\n   28     30       2    0.418  0.0593        0.317        0.552\n   36     28       1    0.403  0.0590        0.302        0.537\n   69     18       1    0.381  0.0599        0.280        0.518\n\n                Adju_TA=1 \n time n.risk n.event survival std.err lower 95% CI upper 95% CI\n    1     61       2    0.967  0.0228        0.924        1.000\n    3     59       4    0.902  0.0381        0.830        0.980\n    6     54       2    0.868  0.0434        0.787        0.958\n    7     52       2    0.835  0.0477        0.746        0.934\n    8     49       1    0.818  0.0497        0.726        0.921\n    9     48       4    0.750  0.0560        0.647        0.868\n   11     42       4    0.678  0.0610        0.569        0.809\n   12     38       6    0.571  0.0652        0.457        0.714\n   13     31       2    0.534  0.0660        0.419        0.681\n   14     29       2    0.497  0.0664        0.383        0.646\n   15     25       2    0.458  0.0668        0.344        0.609\n   17     23       2    0.418  0.0666        0.306        0.571\n   20     19       3    0.352  0.0661        0.243        0.509\n   21     16       1    0.330  0.0655        0.224        0.487\n   24     14       1    0.306  0.0650        0.202        0.464\n   26     12       1    0.281  0.0644        0.179        0.440\n   27     11       1    0.255  0.0634        0.157        0.415\n   28     10       1    0.230  0.0620        0.135        0.390\n   43      9       1    0.204  0.0601        0.115        0.364\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nDFS\n```\n\n::: {.cell-output .cell-output-stdout .hidden}\n\n```\nCall: survfit(formula = Surv(FU_DFS, RECUR == \"1\") ~ Adju_TA, data = HAN)\n\n           n events median 0.95LCL 0.95UCL\nAdju_TA=0 77     43     20      14      NA\nAdju_TA=1 61     42     14      12      21\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nDFS_target_kind<-survfit(Surv(FU_DFS, RECUR==\"1\")~Adju_target, data=HAN)\nsummary(DFS_target_kind)\n```\n\n::: {.cell-output .cell-output-stdout .hidden}\n\n```\nCall: survfit(formula = Surv(FU_DFS, RECUR == \"1\") ~ Adju_target, data = HAN)\n\n                Adju_target=0 \n time n.risk n.event survival std.err lower 95% CI upper 95% CI\n    1     76       1    0.987  0.0131        0.962        1.000\n    2     74       1    0.974  0.0185        0.938        1.000\n    3     72       3    0.933  0.0290        0.878        0.991\n    4     69       3    0.892  0.0360        0.825        0.966\n    5     65       2    0.865  0.0397        0.790        0.946\n    6     63       1    0.851  0.0414        0.774        0.936\n    7     62       1    0.837  0.0430        0.757        0.926\n    8     61       3    0.796  0.0470        0.709        0.894\n    9     57       2    0.768  0.0493        0.678        0.871\n   10     54       4    0.711  0.0532        0.614        0.824\n   11     50       1    0.697  0.0540        0.599        0.812\n   12     48       2    0.668  0.0556        0.568        0.786\n   13     46       2    0.639  0.0568        0.537        0.761\n   14     44       4    0.581  0.0586        0.477        0.708\n   15     40       1    0.566  0.0589        0.462        0.695\n   17     39       1    0.552  0.0592        0.447        0.681\n   18     38       1    0.537  0.0594        0.433        0.667\n   19     36       2    0.508  0.0597        0.403        0.639\n   20     34       1    0.493  0.0598        0.388        0.625\n   23     33       1    0.478  0.0598        0.374        0.611\n   24     32       2    0.448  0.0597        0.345        0.582\n   28     30       2    0.418  0.0593        0.317        0.552\n   36     28       1    0.403  0.0590        0.302        0.537\n   69     18       1    0.381  0.0599        0.280        0.518\n\n                Adju_target=1 \n time n.risk n.event survival std.err lower 95% CI upper 95% CI\n    1     42       2    0.952  0.0329        0.890        1.000\n    3     40       3    0.881  0.0500        0.788        0.985\n    6     37       1    0.857  0.0540        0.758        0.970\n    7     36       2    0.810  0.0606        0.699        0.937\n    8     34       1    0.786  0.0633        0.671        0.920\n    9     33       1    0.762  0.0657        0.643        0.902\n   11     31       3    0.688  0.0718        0.561        0.844\n   12     28       4    0.590  0.0766        0.457        0.761\n   13     24       1    0.565  0.0772        0.433        0.739\n   15     21       2    0.511  0.0787        0.378        0.691\n   17     19       2    0.458  0.0791        0.326        0.642\n   20     15       2    0.397  0.0794        0.268        0.587\n   21     13       1    0.366  0.0790        0.240        0.559\n   24     12       1    0.336  0.0781        0.213        0.529\n   27     11       1    0.305  0.0767        0.186        0.499\n   28     10       1    0.275  0.0748        0.161        0.468\n   43      9       1    0.244  0.0725        0.136        0.437\n\n                Adju_target=2 \n time n.risk n.event survival std.err lower 95% CI upper 95% CI\n    3     19       1    0.947  0.0512       0.8521        1.000\n    6     17       1    0.892  0.0724       0.7604        1.000\n    9     15       3    0.713  0.1088       0.5290        0.962\n   11     11       1    0.648  0.1166       0.4558        0.923\n   12     10       2    0.519  0.1242       0.3244        0.830\n   13      7       1    0.445  0.1267       0.2544        0.777\n   14      6       2    0.296  0.1202       0.1339        0.656\n   20      4       1    0.222  0.1107       0.0838        0.590\n   26      1       1    0.000     NaN           NA           NA\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nplot(DFS_target_kind, main=\"Progression free survival, Kind of target agent\", xlab=\"Time\", ylab=\"Survival Probability\", col=c(\"blue\", \"red\",\"green\"), lty=c(1,2))\nlegend(\"topright\", legend=c(\"None\",\"Bevacizumab\",\"Cetuximab\"), col=c(\"blue\", \"red\",\"green\"), lty=c(1,2), cex=0.8)\n\nggsurvplot(DFS_target_kind, \n           legend=c(0.8,0.8),\n           pval=TRUE, \n           xlim=c(0,60),\n           break.time.by = 12,\n           legend.labs = \n             c(\"None\", \"Bevacizumab\",\"Cetuximab\"))\n```\n\n```{.r .cell-code .hidden}\nPFS<-ggsurvplot(\n  DFS,                     # survfit object with calculated statistics.\n  pval = TRUE,             # show p-value of log-rank test.\n  conf.int = FALSE,        # show confidence intervals for \n  # point estimaes of survival curves.\n  conf.int.style = \"step\",  # customize style of confidence intervals\n  xlab = \"Time in months\",   # customize X axis label.\n  break.time.by = 12,     # break X axis in time intervals by 200.\n  ggtheme = theme_light(), # customize plot and risk table with a theme.\n  risk.table = \"abs_pct\",  # absolute number and percentage at risk.\n  risk.table.y.text.col = T,# colour risk table text annotations.\n  risk.table.y.text = FALSE,# show bars instead of names in text annotations\n  # in legend of risk table.\n  ncensor.plot = FALSE,      # plot the number of censored subjects at time t\n  #surv.median.line = \"hv\",  # add the median survival pointer.\n  legend.labs = \n    c(\"Adjuvant target agent, No\", \"Yes\"),    # change legend labels.\n  palette = \n    c(\"#E7B800\", \"#2E9FDF\"), # custom color palettes.\n  fun = NULL, #Cumulative risk\n  xlim = c(0, 72)\n)\nPFS\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nOS<-survfit(Surv(FU_OS, DEATH==\"1\")~Adju_TA, data=HAN)\nOS_all<-survfit(Surv(FU_OS, DEATH==\"1\")~1, data=HAN)\nsummary(OS_all)\nOS\n\nOS_TA<-ggsurvplot(\n  OS,                     # survfit object with calculated statistics.\n  pval = TRUE,             # show p-value of log-rank test.\n  conf.int = FALSE,        # show confidence intervals for \n  # point estimaes of survival curves.\n  conf.int.style = \"step\",  # customize style of confidence intervals\n  xlab = \"Time in months\",   # customize X axis label.\n  break.time.by = 12,     # break X axis in time intervals by 200.\n  ggtheme = theme_light(), # customize plot and risk table with a theme.\n  risk.table = \"abs_pct\",  # absolute number and percentage at risk.\n  risk.table.y.text.col = T,# colour risk table text annotations.\n  risk.table.y.text = FALSE,# show bars instead of names in text annotations\n  # in legend of risk table.\n  ncensor.plot = FALSE,      # plot the number of censored subjects at time t\n  #surv.median.line = \"hv\",  # add the median survival pointer.\n  legend.labs = \n    c(\"Adjuvant target agent, No\", \"Yes\"),    # change legend labels.\n  palette = \n    c(\"#E7B800\", \"#2E9FDF\"), # custom color palettes.\n  fun = NULL, #Cumulative risk\n  xlim = c(0, 72)\n)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nlibrary(dplyr)\nlibrary(MatchIt)\n\nHAN_IPTW<-as.data.frame(HAN[,c(\"MRN\",\"Adju_TA\",\"Adju_target\",\"Male\",\"AGE60\",\"CCI7\",\"ASA3\",\"RTCOL\",\"LNR\",\"pT4\",\"Pni1\",\"Lvi1\",\"Vi1\",\"PD\",\"BILOBE\",\"MULTI4\",\"SIZE4\"\n                               ,\"CEA73\",\"M1_12m\",\"PreHR_chemo\",\"PreHR_TA\",\"FU_DFS\",\"RECUR\")])\n\n\n## DATA character change ###\nHAN_IPTW$Male <-as.factor(HAN_IPTW$Male)\nHAN_IPTW$AGE60 <-as.factor(HAN_IPTW$AGE60)\nHAN_IPTW$CCI7 <-as.factor(HAN_IPTW$CCI7)\nHAN_IPTW$ASA3 <-as.factor(HAN_IPTW$CCI7)\nHAN_IPTW$RTCOL <-as.factor(HAN_IPTW$RTCOL)\nHAN_IPTW$pT4 <-as.factor(HAN_IPTW$pT4)\nHAN_IPTW$Pni1 <-as.factor(HAN_IPTW$Pni1)\nHAN_IPTW$Lvi1 <-as.factor(HAN_IPTW$Lvi1)\nHAN_IPTW$Vi1 <-as.factor(HAN_IPTW$Vi1)\nHAN_IPTW$PD <-as.factor(HAN_IPTW$PD)\nHAN_IPTW$BILOBE <-as.factor(HAN_IPTW$BILOBE)\nHAN_IPTW$MULTI4 <-as.factor(HAN_IPTW$MULTI4)\nHAN_IPTW$SIZE4 <-as.factor(HAN_IPTW$SIZE4)\nHAN_IPTW$CEA73 <-as.factor(HAN_IPTW$CEA73)\nHAN_IPTW$M1_12m <-as.factor(HAN_IPTW$M1_12m)\nHAN_IPTW$PreHR_TA <-as.factor(HAN_IPTW$PreHR_TA)\n\n\n\ntable1_iptw <- mytable(Adju_TA~Adju_target+Male+AGE60+CCI7+ASA3+RTCOL+LNR+pT4+Pni1+Lvi1+Vi1+PD+BILOBE+MULTI4+SIZE4+CEA73+M1_12m+PreHR_TA,\n                       show.total=TRUE, exact=TRUE, data=HAN_IPTW, method = 3)\n\ntable1_iptw\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n## Calculating propensity score ###\n\nfit_IPTW<-glm(Adju_TA~Male+AGE60+ASA3+RTCOL+LNR+pT4+Pni1+Lvi1+Vi1+PD+BILOBE+MULTI4+SIZE4+CEA73+M1_12m+PreHR_TA, family=binomial, data=HAN_IPTW)\nfactor<-extractOR(fit_IPTW, digits=3)\nfactor\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                OR   lcl     ucl      p\n(Intercept)  1.797 0.379   8.513 0.4602\nMale1        0.892 0.347   2.288 0.8114\nAGE601       0.796 0.105   6.061 0.8259\nASA3CCI>7    1.176 0.149   9.296 0.8779\nRTCOL1       1.777 0.590   5.350 0.3064\nLNR          3.406 0.308  37.646 0.3174\npT41         0.470 0.129   1.713 0.2524\nPni11        1.324 0.515   3.399 0.5601\nLvi11        0.525 0.194   1.424 0.2059\nVi11         1.712 0.641   4.569 0.2832\nPD1          0.932 0.119   7.292 0.9462\nBILOBE1      0.346 0.112   1.073 0.0661\nMULTI41      4.075 1.089  15.249 0.0370\nSIZE41       1.388 0.450   4.281 0.5682\nCEA731       1.443 0.365   5.707 0.6014\nM1_12mM1     0.188 0.053   0.659 0.0091\nPreHR_TA1   24.975 4.641 134.397 0.0002\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nsummary(fit_IPTW)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = Adju_TA ~ Male + AGE60 + ASA3 + RTCOL + LNR + pT4 + \n    Pni1 + Lvi1 + Vi1 + PD + BILOBE + MULTI4 + SIZE4 + CEA73 + \n    M1_12m + PreHR_TA, family = binomial, data = HAN_IPTW)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept)  0.58611    0.79363   0.739 0.460198    \nMale1       -0.11478    0.48094  -0.239 0.811373    \nAGE601      -0.22772    1.03555  -0.220 0.825948    \nASA3CCI>7    0.16211    1.05487   0.154 0.877865    \nRTCOL1       0.57511    0.56224   1.023 0.306364    \nLNR          1.22567    1.22582   1.000 0.317372    \npT41        -0.75539    0.66004  -1.144 0.252427    \nPni11        0.28041    0.48122   0.583 0.560094    \nLvi11       -0.64350    0.50872  -1.265 0.205893    \nVi11         0.53757    0.50090   1.073 0.283185    \nPD1         -0.07083    1.04981  -0.067 0.946208    \nBILOBE1     -1.06017    0.57683  -1.838 0.066075 .  \nMULTI41      1.40478    0.67336   2.086 0.036958 *  \nSIZE41       0.32797    0.57464   0.571 0.568178    \nCEA731       0.36650    0.70162   0.522 0.601412    \nM1_12mM1    -1.67374    0.64154  -2.609 0.009082 ** \nPreHR_TA1    3.21786    0.85866   3.748 0.000179 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 189.45  on 137  degrees of freedom\nResidual deviance: 142.96  on 121  degrees of freedom\nAIC: 176.96\n\nNumber of Fisher Scoring iterations: 5\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nwrite.csv(factor, file=\"fit_PTR.csv\")\n\nHAN_IPTW$pr.score <- predict(fit_IPTW, type = \"response\") ##attach propensity score##\n#HAN_IPTW$att.weights <- with(HAN_IPTW, Adju_TA + (1-Adju_TA)*pr.score/(1-pr.score))\nHAN_IPTW$ate.weights <- ifelse(HAN_IPTW$Adju_TA==\"1\", 1/HAN_IPTW$pr.score, 1/(1-HAN_IPTW$pr.score))\n\n## Goodness of Fit test, Hosmer Lemeshow test ####\n#install.packages(\"ResourceSelection\")\nlibrary(ResourceSelection)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nResourceSelection 0.3-6 \t 2023-06-27\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nhoslem.test(HAN_IPTW$Adju_TA, fitted(fit_IPTW))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tHosmer and Lemeshow goodness of fit (GOF) test\n\ndata:  HAN_IPTW$Adju_TA, fitted(fit_IPTW)\nX-squared = 7.4342, df = 8, p-value = 0.4906\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nlibrary(pROC)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nType 'citation(\"pROC\")' for a citation.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n\nAttaching package: 'pROC'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nThe following objects are masked from 'package:stats':\n\n    cov, smooth, var\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#install.packages(\"Epi\")\nrequire(Epi)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nLoading required package: Epi\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#install.packages(\"pROC\")\na1=ROC(form=Adju_TA~pr.score, data=HAN_IPTW, plot = \"ROC\") ## discrimination of TA NO vs. TA YES group by propensity score ##\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/ROC_curve-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nlibrary (WeightIt)\nlibrary(cobalt)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n cobalt (Version 4.5.5, Build Date: 2024-04-02)\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n\nAttaching package: 'cobalt'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nThe following object is masked from 'package:MatchIt':\n\n    lalonde\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\ncovs <- subset(HAN_IPTW, select = c(Male,AGE60,ASA3,RTCOL,LNR,pT4,Pni1,Lvi1,Vi1,PD,BILOBE,MULTI4,SIZE4,CEA73,M1_12m,PreHR_TA))\n\n#W.out_att <- weightit(Adju_TA~covs, data=HAN_IPTW, method=\"ps\", estimand = \"ATT\") ##table#\n#bal.tab(W.out_att, un=TRUE, binary=\"std\", thresholds=0.2)\n\nW.out_ate <- weightit(Adju_TA~covs, data=HAN_IPTW, method=\"ps\", estimand = \"ATE\") ##table#\nbal.tab(W.out_ate, un=TRUE, binary=\"std\", thresholds=0.2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBalance Measures\n               Type Diff.Un Diff.Adj    M.Threshold\nprop.score Distance  1.3000  -0.0544 Balanced, <0.2\nMale         Binary -0.0563  -0.0099 Balanced, <0.2\nAGE60        Binary  0.0226   0.0634 Balanced, <0.2\nASA3_CCI>7   Binary  0.0102   0.0667 Balanced, <0.2\nRTCOL        Binary -0.0473   0.0213 Balanced, <0.2\nLNR         Contin. -0.0224   0.0065 Balanced, <0.2\npT4          Binary -0.2646   0.0494 Balanced, <0.2\nPni1         Binary -0.1208  -0.0207 Balanced, <0.2\nLvi1         Binary -0.4092   0.0271 Balanced, <0.2\nVi1          Binary -0.1188   0.0829 Balanced, <0.2\nPD           Binary  0.0498  -0.0142 Balanced, <0.2\nBILOBE       Binary -0.1557   0.1381 Balanced, <0.2\nMULTI4       Binary  0.2641   0.1087 Balanced, <0.2\nSIZE4        Binary  0.1845  -0.0309 Balanced, <0.2\nCEA73        Binary  0.1754   0.0711 Balanced, <0.2\nM1_12m_M1    Binary -0.4233  -0.1027 Balanced, <0.2\nPreHR_TA     Binary  0.8984  -0.1044 Balanced, <0.2\n\nBalance tally for mean differences\n                   count\nBalanced, <0.2        17\nNot Balanced, >0.2     0\n\nVariable with the greatest mean difference\n Variable Diff.Adj    M.Threshold\n   BILOBE   0.1381 Balanced, <0.2\n\nEffective sample sizes\n           Control Treated\nUnadjusted   77.     61.  \nAdjusted     32.89   40.16\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nlove.plot(W.out_ate, thresholds = c(m = .1), var.order = \"unadjusted\")\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Standardized mean differences and raw mean differences are present in the same plot. \nUse the `stars` argument to distinguish between them and appropriately label the x-axis.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/Love_plots-1.png){width=672}\n:::\n\n```{.r .cell-code .hidden}\n## Love plot 2, # balance plot#, Figure 1##\nv<- data.frame(old=c(\"Male\",\"AGE60\",\"ASA3\",\"RTCOL\",\"LNR\",\"pT4\",\"Pni1\",\"Lvi1\",\"Vi1\",\"PD\",\"BILOBE\",\"MULTI4\",\"SIZE4\",\"CEA73\",\"M1_12m\",\"PreHR_TA\",\"ps\"),\n               new=c(\"Male\",\"Age>60\",\"ASA >3\",\"Primary tumor at Rt colon\",\"Regional LN ratio\",\"pT4\", \"Perineural invasion of PT\",\n                    \"Lymphatic invasion of PT\",\"Vascular invasion of PT\", \"Poor differentiated\", \"Bilobar involvement of CRLM\", \n                    \"Number of CRLM>4\", \"Max size of CRLM>4cm\", \"Pre-hepatectomy CEA>73\", \"Synch or LM within 12mon\",\"Neoaduvant target agent\", \"propensity score\"))\n\nlove.plot(W.out_ate, stats = c(\"mean.diffs\"), \n          threshold = c(m = .2), \n          binary = \"std\", abs = TRUE,\n          var.order = \"unadjusted\",\n          var.names = v,\n          limits = c(0, 1), grid = TRUE, wrap = 20,\n          sample.names = c(\"Original\", \"Weighted\"),\n          position = \"top\",\n          line= TRUE,\n          shapes = c(\"circle\", \"triangle\"),\n          colors = c(\"red\", \"blue\"))+\n  labs(x=\"Absolute standadized mean difference\")+\n  theme(legend.position = c(.75, .3),\n        legend.box.background = element_rect(), \n        legend.box.margin = margin(0.5, 1, 1, 1),\n        legend.title=element_blank(),\n        plot.title=element_blank(),\n        axis.title=element_text(color = \"black\", size=10))\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: A numeric `legend.position` argument in `theme()` was deprecated in ggplot2\n3.5.0.\nℹ Please use the `legend.position.inside` argument of `theme()` instead.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/Love_plots-2.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nlibrary(tableone)\n#install.packages(\"survey\")\nlibrary(survey)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nLoading required package: grid\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nLoading required package: Matrix\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n\nAttaching package: 'survey'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nThe following object is masked from 'package:WeightIt':\n\n    calibrate\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nThe following object is masked from 'package:graphics':\n\n    dotchart\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nvars <- c(\"Male\",\"AGE60\",\"ASA3\",\"RTCOL\",\"LNR\",\"pT4\",\"Pni1\",\"Lvi1\",\"Vi1\",\"PD\",\"BILOBE\",\"MULTI4\",\"SIZE4\",\"CEA73\",\"M1_12m\",\"PreHR_TA\")\n\ntab.unwt <- CreateTableOne(vars=vars, strata=\"Adju_TA\", data=HAN_IPTW, test =FALSE)\nprint(tab.unwt, smd=TRUE)\n\nSvy <- svydesign(ids = ~ 1, data = HAN_IPTW, weights = ~ ate.weights)\nsummary(Svy)\nSvy\ntab.wt <- svyCreateTableOne(vars=vars, strata=\"Adju_TA\", data=Svy, test =FALSE)\nprint(tab.wt, smd=TRUE)\n\nlibrary(jskm)   \n\nunadjusteDFS<-survfit(Surv(HAN_IPTW$FU_DFS, as.numeric(HAN_IPTW$RECUR)) ~ HAN_IPTW$Adju_TA, data=HAN_IPTW)\nsummary(unadjusteDFS)\n\niptwsvyDFS <- svydesign(ids = ~ 1, data = HAN_IPTW, weights = ~ ate.weights)\n\niptwDFS<-svykm(Surv(FU_DFS,RECUR)~Adju_TA, design=iptwsvyDFS, data=HAN_IPTW)\n\niptwDFS\n\na<-jskm(unadjusteDFS, timeby = 12, ystratalabs=c('No',\"Yes\"),\n        ystrataname = \"Adjuvant Target therapy\", table = TRUE, ci=FALSE, pval=FALSE,\n        xlabs=\"Months after Surgery\", main =\"Unadjusted\",\n        dashed=FALSE,marks=FALSE,xlims=c(0,60),legendposition=c(0.85,0.85))\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 22 rows containing missing values or values outside the scale range\n(`geom_step()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 16 rows containing missing values or values outside the scale range\n(`geom_text()`).\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\na\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/TableOne_package-1.png){width=672}\n:::\n\n```{.r .cell-code .hidden}\nb<-svyjskm(iptwDFS, timeby = 12, ystratalabs=c('No',\"Yes\"),\n           ystrataname = \"Adjuvant Target therapy\", table = TRUE, ci=FALSE, pval=FALSE,\n           xlabs=\"Months after Surgery\", main =\"Weighted\",\n           dashed=FALSE,marks=TRUE,xlims=c(0,60),legendposition=c(0.85,0.85))\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 22 rows containing missing values or values outside the scale range\n(`geom_step()`).\nRemoved 16 rows containing missing values or values outside the scale range\n(`geom_text()`).\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nb\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/TableOne_package-2.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#### Univarate Cox regression, unweighted, weighted ######################\n\nHAN_IPTW$TS_DFS=Surv(HAN_IPTW$FU_DFS, HAN_IPTW$RECUR==\"1\") #time object\n\n## Uni, unweighted\nout = mycph(TS_DFS~Adju_TA+Adju_target+Male+AGE60+ASA3+RTCOL+LNR+pT4+Pni1+Lvi1+Vi1+PD+BILOBE+MULTI4+SIZE4+CEA73+M1_12m+PreHR_TA, digits=2, data=HAN_IPTW)\nout\nwrite.csv(out, file=\"Cox_uni.csv\")\n\n\n## Uni, weighted\n# uni_ate = mycphwt(TS_DFS~Adju_TA+Adju_target+Male+AGE60+ASA3+RTCOL+LNR+pT4+Pni1+Lvi1+Vi1+PD+BILOBE+MULTI4+SIZE4+CEA73+M1_12m+PreHR_TA, digits=2, data=HAN_IPTW)\nuni_ate = mycph(TS_DFS~Adju_TA+Adju_target+Male+AGE60+ASA3+RTCOL+LNR+pT4+Pni1+Lvi1+Vi1+PD+BILOBE+MULTI4+SIZE4+CEA73+M1_12m+PreHR_TA, digits=2, data=HAN_IPTW)\nuni_ate\nwrite.csv(uni_ate, file=\"Cox_uni_ate.csv\")\n\n##### Multivariate Cox regression, unweighted, weighted #################\n\n## unweighted multi cox\nCOX<-coxph(TS_DFS~Adju_TA+Vi1+BILOBE+MULTI4+CEA73+PreHR_TA, data=HAN_IPTW)\nCOX<-coxph(TS_DFS~Adju_target+Vi1+BILOBE+MULTI4+CEA73+PreHR_TA, data=HAN_IPTW)\nsummary(COX)\nextractHR(COX)\n\nCOX_step<-step(COX, direction=\"backward\")\nextractHR(COX_step, digit=2)\n\n## weighted multi cox###\n## ATE ###\nmulti_ate<-coxph(TS_DFS~Adju_TA+Male+LNR+Pni1+Vi1+BILOBE+MULTI4+CEA73, weights=ate.weights, data=HAN_IPTW)\nmulti_ate<-coxph(TS_DFS~Adju_target+Male+LNR+Pni1+Vi1+BILOBE+MULTI4+CEA73, weights=ate.weights, data=HAN_IPTW)\nsummary(multi_ate)\n#원래코드에서는 extractHRwt 였으나 함수의 source 코드가 없어서 extractHR로 변경함 \n#extractHRwt(multi_ate)\nextractHR(multi_ate)\n\nWt_step<-step(multi_ate, direction=\"backward\")\nsummary(Wt_step)\n\n#t.step<-extractHRwt(Wt_step, digit=2)\nt.step<-extractHR(Wt_step, digit=2)\nt.step\nwrite.csv(t.step, file=\"multi_Cox_wt.csv\")\n```\n:::\n\n\n## Introduction\n\nResectability가 있는 대장암의 간 전이에 대한 가장 효과적인 치료법은 전이부위를 포함하는 절제 수술과 perioperative chemotherapy으로 제시되고 있습니다. 하지만, 수술 후 재발률이 18개월 이내 75%까지 보고될 만큼 매우 높습니다 [@RN671].\n\n이에 항암화학요법에 표적 치료제를 추가하는 것에 대해 몇 몇 study가 보고되었으나 대규모의 높은 등급의 study는 아직 부족한 상태입니다. 이러한 study 에 따르면, 수술 후 표적치료제의 추가는 생존 이득이 없거나 오히려 유해한 결과로 나타났다고 보고되었습니다.\n\n그러나 아직까지 국내 보험체계는 전이 부위를 포함하는 절제술 후 항암요법에 표적치료제를 추가하는 것에 제한이 없는 상황입니다.\n\n따라서 대장암의 간 전이에서 근치적 절제술 후 항암화학요법을 진행한 환자에 대한 분석을 진행하여 표적치료제의 영향력을 평가하고자 하였습니다\n\n## Methods\n\n### Patients\n\n본 연구는 후향적 연구로 2009년 1월부터 2022년 7월까지 원자력병원에서 시행한 대장암 간 전이에 대한 근치적 목적의 절제 수술 케이스를 대상으로 하였습니다.\n\n이 중 FOLFOX FOLFIRI 등 Doublet chemotherapy를 시행한 케이스를 포함 하였으며, 타 장기 전이가 있거나, R1/2 절제의 경우, 항암치료를 받지 않거나 단일제제 항암치료 케이스는 제외하였습니다.\n\n최종적으로 138개의 케이스에 대해 분석이 진행되었으며, Primary end point 는 간 전이 절제술로부터 progression free survival 로 설정하였습니다.\n\n### Statistical analyses\n\n후향적 연구의 한계를 보정하기 위한 통계적 기법으로서 IPTW 를 적용하였습니다. 대상이 되는 138개의 original cohort 에 대해 다변량 로지스틱 회귀 분석을 통해 propensity score와 가중치 를 계산하여 가중치를 적용하여 보정한 데이터셋을 얻었습니다. 이렇게 보정된 weighted cohort 에 대해서 Absolute SMD 값을 통해 치료군과 대조군의 balance 를 확인하였습니다.\n\n최종적으로 original cohort 와 weighted cohort 에서 콕스 회귀 분석을 시행하였으며 다변량 회귀분석에서는 후향 제거법을 사용하여 수술 후 표적치료제가 갖는 예후에의 영향력을 평가하였습니다.\n\nPropensity score 를 구하기 위해 활용된 로지스틱 회귀분석에 적용된 변수는 다음과 같습니다. 환자 factor 로서 성별, 연령, ASA score 등 Primary tumor factor 로서 tumor location, lymph node ratio 등 Metastatic factor 로서 간엽 침범 정도, 전이 병변의 개수 등을 설정하였습니다. 이에 따라 Propensity score 에 따른 allocation probability 의 AUC 는 0.811, p-value 는 0.4906 로 나타났습니다 (@fig-ROC).\n\n\n::: {#cell-fig-ROC .cell}\n\n```{.r .cell-code .hidden}\nROC(form=Adju_TA~pr.score, data=HAN_IPTW, plot = \"ROC\")\n```\n\n::: {.cell-output-display}\n![Propensity score 에 따른 allocation probability 의 AUC](index_files/figure-html/fig-ROC-1.png){#fig-ROC width=576}\n:::\n:::\n\n\nAll analyses were performed using R version 4.4.1 (R Core Team (2021). (R: A language and environment for statistical computing. R Foundation for Statistical Computing, Vienna, Austria).\n\n## Results\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\ntable1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n                    Descriptive Statistics by 'Adju_TA'                    \n———————————————————————————————————————————————————————————————————————————— \n                           0                1              Total         p  \n                         (N=77)           (N=61)          (N=138)     \n———————————————————————————————————————————————————————————————————————————— \n AGE                  59.0 ± 10.5      59.1 ±  9.0      59.1 ±  9.8    0.974\n Male                                                                  0.888\n   - 0                 22 (28.6%)       19 (31.1%)       41 (29.7%)         \n   - 1                 55 (71.4%)       42 (68.9%)       97 (70.3%)         \n Synch_M1                                                              0.121\n   - M0                12 (15.6%)       17 (27.9%)       29 (21.0%)         \n   - M1                65 (84.4%)       44 (72.1%)      109 (79.0%)         \n M1_12m                                                                0.025\n   - M0                7 ( 9.1%)        15 (24.6%)       22 (15.9%)         \n   - M1                70 (90.9%)       46 (75.4%)      116 (84.1%)         \n ASA3                                                                  0.382\n   - 0                 60 (77.9%)       52 (85.2%)      112 (81.2%)         \n   - 1                 17 (22.1%)       9 (14.8%)        26 (18.8%)         \n CCI7                                                                  1.000\n   - CCI<7             37 (48.1%)       29 (47.5%)       66 (47.8%)         \n   - CCI>7             40 (51.9%)       32 (52.5%)       72 (52.2%)         \n RTCOL                                                                 0.961\n   - 0                 63 (81.8%)       51 (83.6%)      114 (82.6%)         \n   - 1                 14 (18.2%)       10 (16.4%)       24 (17.4%)         \n LNR                 0.1 [ 0.0; 0.2]  0.1 [ 0.0; 0.3]  0.1 [ 0.0; 0.3] 0.476\n pT4                                                                   0.211\n   - 0                 64 (83.1%)       56 (91.8%)      120 (87.0%)         \n   - 1                 13 (16.9%)       5 ( 8.2%)        18 (13.0%)         \n Pni1                                                                  0.599\n   - 0                 46 (59.7%)       40 (65.6%)       86 (62.3%)         \n   - 1                 31 (40.3%)       21 (34.4%)       52 (37.7%)         \n Lvi1                                                                  0.032\n   - 0                 42 (54.5%)       45 (73.8%)       87 (63.0%)         \n   - 1                 35 (45.5%)       16 (26.2%)       51 (37.0%)         \n Vi1                                                                   0.619\n   - 0                 54 (70.1%)       46 (75.4%)      100 (72.5%)         \n   - 1                 23 (29.9%)       15 (24.6%)       38 (27.5%)         \n PD                                                                    1.000\n   - 0                 74 (96.1%)       58 (95.1%)      132 (95.7%)         \n   - 1                 3 ( 3.9%)        3 ( 4.9%)        6 ( 4.3%)          \n BILOBE                                                                0.468\n   - 0                 46 (59.7%)       41 (67.2%)       87 (63.0%)         \n   - 1                 31 (40.3%)       20 (32.8%)       51 (37.0%)         \n MULTI4                                                                0.183\n   - 0                 65 (84.4%)       45 (73.8%)      110 (79.7%)         \n   - 1                 12 (15.6%)       16 (26.2%)       28 (20.3%)         \n SIZE4                                                                 0.392\n   - 0                 66 (85.7%)       48 (78.7%)      114 (82.6%)         \n   - 1                 11 (14.3%)       13 (21.3%)       24 (17.4%)         \n preHR_CEA           9.2 [ 3.2;25.1]  7.3 [ 4.8;44.4]  8.3 [ 3.7;28.0] 0.394\n CEA73                                                                 0.445\n   - 0                 70 (90.9%)       52 (85.2%)      122 (88.4%)         \n   - 1                 7 ( 9.1%)        9 (14.8%)        16 (11.6%)         \n PreHR_chemo                                                           0.028\n   - 0                 61 (79.2%)       37 (60.7%)       98 (71.0%)         \n   - 1                 16 (20.8%)       24 (39.3%)       40 (29.0%)         \n PreHR_TA                                                              0.000\n   - 0                 75 (97.4%)       40 (65.6%)      115 (83.3%)         \n   - 1                 2 ( 2.6%)        21 (34.4%)       23 (16.7%)         \n Post_HR_target_all                                                    0.000\n   - Avastin            0 ( 0.0%)       42 (68.9%)       42 (30.4%)         \n   - Erbitux            0 ( 0.0%)       19 (31.1%)       19 (13.8%)         \n   - None             77 (100.0%)        0 ( 0.0%)       77 (55.8%)         \n———————————————————————————————————————————————————————————————————————————— \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nnumber_of_patients_included <- nrow(HAN)\nnumber_of_Adju_TA_no<-nrow(subset(HAN, Adju_TA==0))\nnumber_of_Adju_TA_yes<-nrow(subset(HAN, Adju_TA==1))\n```\n:::\n\n\nTable 1은 연구에 포함된 환자 특성입니다. 138 개의 케이스에서 대조군의 크기는 77, 치료군의 크기는 61 명 이었습니다. 이 중, 표적치료제가 사용된 61명 중 베바시주맙이 42, 세툭시맙이 19명 이었습니다. 조사된 변수는 patient factor와 primary tumor factor, 그리고 metastases factor 로 구분하였습니다.\n\n연령은 치료군과 대조군 모두 59세 전후로 나타났으며 연령 및 성별에 있어 두 군 간의 통계적인 차이는 없었습니다. 진단 당시 간 전이를 동반하였거나 원발 부위 종양 절제술 후 12개월 이내에 간전이가 발견된 경우는 대조군에서 빈도가 유의하게 높았습니다. 또한 간 절제술 전 항암화학요법 혹은 표적치료제를 사용한 경우는 치료군에서 빈도가 유의하게 높았습니다.\n\n![Table 1. Baseline characteristics for patients with targeted therapy after surgical resection of colorectal liver metastasis](images/clipboard-3145534320.png){width=\"700\"}\n\nPrimary tumor factor 에서는 pathology 소견 상 lymphatic invasion 을 보인 경우 대조군의 빈도가 유의하게 높았습니다. Metastases factor 에서는 병변의 양엽 침범 여부와 개수, 최대 직경에 대해 조사하였고 두 군 간의 유의한 차이는 없었습니다. 따라서 raw data에서는 치료군과 대조군 간의 불균형이 관찰됩니다.\n\n따라서 propensity score를 사용해 가중치를 적용하여 데이터셋을 보정하는 IPTW 기법을 적용하였습니다.\n\nFigure 2은, original cohort 와 weighted cohort 의 absolute SMD 를 나타낸 것으로 빨간색 범례가 보정 전 특성을 나타내고, 파란색 범례가 보정 후 특성을 나타냅니다. 가중치 적용 후 absolute SMD 값이 0.2 이하로 조정되어 보정 후 치료군과 대조군이 적절한 balance 를 이루고 있는 것을 확인할 수 있습니다.\n\n![Figure 2. Absolute SMD, Balance at original cohort & weighted cohort](images/clipboard-2590844408.png)\n\nFigure 3은 연구에 포함된 환자 에 대한 Kaplan Meier 생존곡선입니다. 왼쪽은 metastases 에 대한 progression survival 을 나타내고 오른쪽은 overall survival 을 나타냅니다. f/u 기간의 중앙값은 45.5개월 이었으며, 관찰기간 중의 PFS event 는 85건, OS event 는 67건 이었습니다.\n\n![Figure 3. Kaplan Meier Analysis, original cohort](images/clipboard-3783060595.png)\n\n테이블 2는 단변량 콕스 회귀 분석 결과입니다. 먼저 가중치를 적용하지 않은 original cohort 에서는 수술 전 CEA level 이 높은 경우, 수술 전 표적치료제 적용한 경우, vascular invasion 이 진행된 경우, 전이 병변이 간 양엽을 모두 침범한 경우, 간 전이 병변의 개수가 4개 이상일 경우에서 통계적으로 유의한 Poor prognostic factor 로 조사되었습니다.수술 후 표적치료제의 사용여부는 불량한 예후를 시사하는 경향을 보였으나 통계적으로 유의하지는 않았습니다.\n\nWeighted cohort 에서는 보정 전 그룹과 비교하여 vascular invasion 이 있는 경우에서 Hazard ratio 1.70 으로 통계적으로 유의한 Poor prognostic factor 로 조사되었습니다. 보정 후에도 수술 후 표적치료제의 사용에 대한 경우는 불량한 예후를 시사하는 경향을 보였으나 통계적으로 유의하지는 않았습니다.\n\n![Table 2. Uni-variated Cox regression associated to PFS](images/clipboard-3985066224.png)\n\nTable 3 는 다변량 콕스 회귀 분석 결과입니다. original cohort 에서는 간 전이 절제술 전 표적치료제를 사용한 경우, Vascular invasion 이 있는 경우, 전이 병변이 간 양엽을 모두 침범한 경우에서 통계적으로 유의한 Poor prognostic factor 로 조사되었습니다. 반면 Weighted cohort 에서는 Perineural invasion 여부와 더불어 수술 후 표적치료제의 사용이 유의한 poor prognostic factor 로 조사되었습니다.\n\n![Table 3. multi-variated Cox regression associated to PFS](images/clipboard-1312926093.png)\n\n## Conclusion\n\n결론적으로 대장암 환자의 간절제술 후 항암치료에 표적 치료제를 추가하는 것은 생존 이점이 없으며, 오히려, 전이절제술 후 표적 치료제 사용이 progression 에 있어 해로운 영향력이 있을 수 있음을 확인하였습니다.\n\n## Discussion\n\n이러한 표적치료제의 사용이 해로울 수 있는 가능성은, 2014년 LANCET oncology 에 게재된 New EPOC study에서 언급된 내용으로, 이 분석 결과를 통해 해당 내용을 데이터로 확인할 수 있었습니다 [@RN672].\n\n다만, 분석에 포함된 대상군의 크기가 제한적이었고, 실시된 표적치료제 별 분석이 이루어지지 않았습니다. 또한, 후향적 연구의 한계로서 unmeasured confounder 가 존재하여 분석의 한계가 있을 수 있겠습니다.\n\n따라서 절제 가능한 대장암 환자에 대해 수술 후 최적의 표적 치료제 적용에 대한 대규모 전향적 연구가 필요할 것으로 사료됩니다.\n\n\n::: {.cell}\n\n:::\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}